CREATE DATABASE TASK8_DB;
USE TASK8_DB;
CREATE TABLE STUDENTS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (100),
    MARKS INT 
);

INSERT INTO STUDENTS (NAME,MARKS) VALUES
('ANAMIKA', 75),
('RAJ',50),
('SIMRAN',88),
('AMAN',40);

-- CREATE A STORED PROCEDURE
DELIMITER //
CREATE PROCEDURE GETHIGHSCORERS(IN MINMARKS INT)
BEGIN
SELECT*FROM STUDENTS WHERE MARKS > MINMARKS;
END //
DELIMITER ;

-- TO CALL THE PROCEDURE
CALL GETHIGHSCORERS(60);

-- CREATE A FUNCTION

DELIMITER //

CREATE FUNCTION GetGrade(marks INT)
RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
  DECLARE grade VARCHAR(10);
  IF marks >= 75 THEN
    SET grade = 'A';
  ELSEIF marks >= 60 THEN
    SET grade = 'B';
  ELSEIF marks >= 50 THEN
    SET grade = 'C';
  ELSE
    SET grade = 'Fail';
  END IF;
  RETURN grade;
END //

DELIMITER ;

-- TO TEST THE FUNCTION

SELECT NAME, MARKS, GETGRADE(MARKS) AS GRADE 
FROM STUDENTS;